name: MAX Firmware CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]   # triggers when a new release is published

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          idf.py build

      - name: Upload firmware binaries (on release only)
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: max-firmware-${{ github.ref_name }}
          path: |
            build/openair-max.bin
            build/ota_data_initial.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
