name: MAX Firmware CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]   # triggers when a new release is published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          target: esp32c6 
          path: '.'

      - name: Upload firmware binaries (on release only)
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: max-firmware-${{ github.ref_name }}
          path: |
            build/openair-max.bin
            build/ota_data_initial.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
